### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by zilos** [MagicSketch/MagicMirror#32]
Hi @jamztang i know I had this issue before but for some odd reason, the plugin keeps crashing my copy of Sketch every single time. Even i try to check for updates, it crashes Sketch. Im not sure what could be going on. Maybe the security settings on my work computer is making it crash, or it could be the plugin itself on my particular macbook pro, but I cant seem to get MagicMirror to work. If you can help, I would greatly appreciate it. If not, its ok. Ill test it out on a different computer i have at home, but its not a laptop which i need ot use every day. 
Thanks again!

**Comment by jamztang** [comment]
Hi @zilos, I've recently pushed a new version v2.0.6, would you please try if it works for you?

**Comment by zilos** [comment]
@jamztang downloaded the latest release (v.2.0.6), and it still crashes.

**Comment by zilos** [comment]
do you think if i take a video of the incident, would that be helpful?
I cant do screen share because of security issues with my laptop and the company i work for (GE), so maybe I, thinking taking a video of the problem might help?

**Comment by jamztang** [comment]
Yes that can be helpful. It'd be good if you can show along side with the console. 

https://github.com/jamztang/MagicMirror/wiki/Retrieving-Crash-Log

Cheers
James

**Comment by zilos** [comment]
ok i made a video. Ill email you a link to it. 

here is also the crash report on it. 

4/18/16 9:43:13.688 AM	Sketch[50522]	Version 3.7 (28169). Variant is NONAPPSTORE. Config is Release. Crash reporting is enabled. Updating is enabled.
4/18/16 9:44:36.174 AM	Sketch[50522]	CGSReenableUpdate: unbalanced enable/disable update.
4/18/16 9:44:36.176 AM	Sketch[50522]	Backtrace (at 170915):
4/18/16 9:44:36.176 AM	Sketch[50522]	CGSReenableUpdate:  0   CoreGraphics                        0x00007fff9a3f54e6 CGSBacktraceCreate + 112
4/18/16 9:44:36.176 AM	Sketch[50522]	CGSReenableUpdate:  1   CoreGraphics                        0x00007fff9a69fa42 CGSLogBacktrace + 15
4/18/16 9:44:36.176 AM	Sketch[50522]	CGSReenableUpdate:  2   CoreGraphics                        0x00007fff9a47e556 _ZN16CGSUpdateManager20enable_update_legacyEv + 94
4/18/16 9:44:36.176 AM	Sketch[50522]	CGSReenableUpdate:  3   CoreGraphics                        0x00007fff9a47e4f1 CGSReenableUpdate + 35
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  4   QuickLook                           0x00007fff99242721 _Z18QLTryCatchAndCrashU13block_pointerFvvE + 17
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  5   libdispatch.dylib                   0x00007fff947ad700 _dispatch_call_block_and_release + 12
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  6   libdispatch.dylib                   0x00007fff947a9e73 _dispatch_client_callout + 8
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  7   libdispatch.dylib                   0x00007fff947ad5cd _dispatch_queue_drain + 1100
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  8   libdispatch.dylib                   0x00007fff947ad030 _dispatch_queue_invoke + 202
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  9   libdispatch.dylib                   0x00007fff947acbef _dispatch_root_queue_drain + 463
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  10  libdispatch.dylib                   0x00007fff947aca1c _dispatch_worker_thread3 + 91
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  11  libsystem_pthread.dylib             0x00007fff8bce3a9d _pthread_wqthread + 729
4/18/16 9:44:36.177 AM	Sketch[50522]	CGSReenableUpdate:  12  libsystem_pthread.dylib             0x00007fff8bce13dd start_wqthread + 13
4/18/16 9:44:51.197 AM	Sketch[50522]	CGSReenableUpdate: unbalanced enable/disable update.
4/18/16 9:44:51.197 AM	Sketch[50522]	Backtrace (at 170930):
4/18/16 9:44:51.197 AM	Sketch[50522]	CGSReenableUpdate:  0   CoreGraphics                        0x00007fff9a3f54e6 CGSBacktraceCreate + 112
4/18/16 9:44:51.197 AM	Sketch[50522]	CGSReenableUpdate:  1   CoreGraphics                        0x00007fff9a69fa42 CGSLogBacktrace + 15
4/18/16 9:44:51.197 AM	Sketch[50522]	CGSReenableUpdate:  2   CoreGraphics                        0x00007fff9a47e556 _ZN16CGSUpdateManager20enable_update_legacyEv + 94
4/18/16 9:44:51.197 AM	Sketch[50522]	CGSReenableUpdate:  3   CoreGraphics                        0x00007fff9a47e4f1 CGSReenableUpdate + 35
4/18/16 9:44:51.197 AM	Sketch[50522]	CGSReenableUpdate:  4   QuickLook                           0x00007fff99242721 _Z18QLTryCatchAndCrashU13block_pointerFvvE + 17
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  5   libdispatch.dylib                   0x00007fff947ad700 _dispatch_call_block_and_release + 12
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  6   libdispatch.dylib                   0x00007fff947a9e73 _dispatch_client_callout + 8
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  7   libdispatch.dylib                   0x00007fff947ad5cd _dispatch_queue_drain + 1100
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  8   libdispatch.dylib                   0x00007fff947ad030 _dispatch_queue_invoke + 202
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  9   libdispatch.dylib                   0x00007fff947acbef _dispatch_root_queue_drain + 463
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  10  libdispatch.dylib                   0x00007fff947aca1c _dispatch_worker_thread3 + 91
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  11  libsystem_pthread.dylib             0x00007fff8bce3a9d _pthread_wqthread + 729
4/18/16 9:44:51.198 AM	Sketch[50522]	CGSReenableUpdate:  12  libsystem_pthread.dylib             0x00007fff8bce13dd start_wqthread + 13
4/18/16 9:46:51.162 AM	Sketch[50522]	The function ‘CGContextClear’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
4/18/16 9:46:51.178 AM	Sketch[50522]	Looked for URLs on the pasteboard, but found none.
4/18/16 9:46:51.178 AM	Sketch[50522]	Looked for URLs on the pasteboard, but found none.
4/18/16 9:46:51.203 AM	Sketch[50522]	__CFPasteboardIssueSandboxExtensionForPath : sandbox extension creation failed: caller requested extension for path that could not be resolved to an absolute path: [/var/folders/tx/w8dcx5bn0gdcfj41gz8lz6l5bqj1nl/T/temp-42/Screen.png]
4/18/16 9:46:51.204 AM	Sketch[50522]	__CFPasteboardIssueSandboxExtensionForPath : sandbox extension creation failed: caller requested extension for path that could not be resolved to an absolute path: [/var/folders/tx/w8dcx5bn0gdcfj41gz8lz6l5bqj1nl/T/temp-42/Screen.png]
4/18/16 9:46:51.204 AM	Sketch[50522]	__CFPasteboardCreateSandboxExtensionDataFromCFData : failed to obtain sandbox extension data for url [file:///var/folders/tx/w8dcx5bn0gdcfj41gz8lz6l5bqj1nl/T/temp-42/Screen.png]
4/18/16 9:46:51.217 AM	Sketch[50522]	Layout still needs update after calling -[BCTableRowView layout].  BCTableRowView or one of its superclasses may have overridden -layout without calling super. Or, something may have dirtied layout in the middle of updating it.  Both are programming errors in Cocoa Autolayout.  The former is pretty likely to arise if some pre-Cocoa Autolayout class had a method called layout, but it should be fixed.
4/18/16 9:52:33.405 AM	Sketch[50522]	MagicMirror: -[SketchPluginContext observeSelection] [Line 230] observing 1

**Comment by sogen** [comment]
crashing here too, 3.7.2

**Comment by jamztang** [comment]
3.7.2 has been working for me quite a while. What are your system config?

**Comment by zilos** [comment]
@jamztang the video i made is too large. is there another way for me to send this to you? Ill try uploading to a video service but my work place blocks these services. I downloaded the latest one as well, but it still cashes. Could it be that its trying to do something over the internet that my company firewall blocks it?

**Comment by jamztang** [comment]
Is that possible you can put it on Dropbox or CloudApp to generate a public link?

**Comment by zilos** [comment]
@jamztang yes im trying that now, its just that we are blocked from uploading anything to some cloud service due to security risks. Im trying Vimeo now.

**Comment by jamztang** [comment]
And you mentioned firewall of your company. Maybe you can use it somewhere with your mobile data and let me know if that fixes? If that's the case I will have to work with you directly for a custom one that won't crash.. I am getting to bed and will check this thread tomorrow morning

**Comment by zilos** [comment]
so I tried it at home and it works fine, but with the laptop from work (MAC book pro), it always crashes.  thanks again for your help and lets see if we can find a custom solution for this. Thx!

**Comment by zilos** [comment]
@jamztang finally, here is the video - https://vimeo.com/165912906

**Comment by sogen** [comment]
@jamztang hi, 
**Yosemite 10.10.5 (14F1713)
MacBook Pro (13-inch, Mid 2012)
16 GB 1600 MHz DDR3
Intel HD Graphics 4000 1024 MB
**These system config?? or do you need some other data?

I just disabled the plugin and the crashes stopped
Is there a way to disable the update checker? I think it's related to that, because I ran the plugin just as Sketch was starting up and Sketch crashed.

**Comment by jamztang** [comment]
@sogen that's great info, would you help retrieve the crash log also just after Sketch crashes? There's a while I have been upgraded to El Capitan hence I could Reston Yosemite. I hope the update part is the issue here so wouldn't be too hard to fix..

**Comment by jamztang** [comment]
Could not test**

**Comment by sogen** [comment]
ok, sending log in a minute

**Comment by sogen** [comment]
`5/9/16 8:21:47.286 PM Sketch[12039]: Version 3.7.2 (28276). Variant is NONAPPSTORE. Config is Release. Crash reporting is enabled. Updating is enabled.
5/9/16 8:22:43.316 PM Sketch[12046]: Version 3.7.2 (28276). Variant is NONAPPSTORE. Config is Release. Crash reporting is enabled. Updating is enabled.
5/9/16 8:22:48.191 PM Sketch[12046]: MagicMirror: -[SketchPluginContext observeSelection] [Line 230] observing 0
5/9/16 8:22:48.216 PM Sketch[12046]: MagicMirror: +[MagicMirror sharedInstanceWithContext:] [Line 125] sharedInstance: <MagicMirror: 0x6080001141c0>
5/9/16 8:22:48.217 PM Sketch[12046]: MagicMirror: -[MagicMirror configureSelection] [Line 314] configureSelection
5/9/16 8:22:48.220 PM Sketch[12046]: MagicMirror: -[MagicMirror keepAround] [Line 213] keepAround
5/9/16 8:22:48.225 PM Sketch[12046]: stack count: 0
5/9/16 8:22:48.238 PM Sketch[12046]: stack count: 0
5/9/16 8:22:48.264 PM Sketch[12046]: MagicMirror: -[MMWindowController windowDidLoad] [Line 43] MMWindowController did loaded
5/9/16 8:22:48.280 PM Sketch[12046]: MagicMirror: -[MMWindowController windowDidLoad] [Line 57] opening frame: {{241, 4}, {780, 44}} (visible)
5/9/16 8:22:48.295 PM Sketch[12046]: MagicMirror: -[SketchPluginContext windowDidBecomeMain:] [Line 75] windowDidBecomeMain
5/9/16 8:22:48.295 PM Sketch[12046]: MagicMirror: -[SketchPluginContext unobserveSelection] [Line 221] Unobserving 0
5/9/16 8:22:48.397 PM Sketch[12046]: MagicMirror: -[MagicMirror(SketchEventsController) documentDidChange:] [Line 507] document <MSDocument: 0x7fa921618b20>
5/9/16 8:22:48.397 PM Sketch[12046]: MagicMirror: -[SketchPluginContext layerSelectionDidChange:] [Line 199] layerSelectionDidChange: (null)
5/9/16 8:22:48.397 PM Sketch[12046]: MagicMirror: -[SketchPluginContext unobserveSelection] [Line 221] Unobserving 0
5/9/16 8:22:48.398 PM Sketch[12046]: MagicMirror: -[SketchPluginContext observeSelection] [Line 230] observing 0
5/9/16 8:22:48.398 PM Sketch[12046]: stack count: 0
5/9/16 8:22:49.581 PM Sketch[12046]: MagicMirror: -[SketchPluginContext windowDidBecomeMain:] [Line 75] windowDidBecomeMain
5/9/16 8:22:49.581 PM Sketch[12046]: MagicMirror: -[SketchPluginContext unobserveSelection] [Line 221] Unobserving 0
5/9/16 8:22:49.658 PM Sketch[12046]: MagicMirror: -[MagicMirror(SketchEventsController) documentDidChange:] [Line 507] document <MSDocument: 0x7fa921618b20>
5/9/16 8:22:49.658 PM Sketch[12046]: MagicMirror: -[SketchPluginContext layerSelectionDidChange:] [Line 199] layerSelectionDidChange: (null)
5/9/16 8:22:49.658 PM Sketch[12046]: MagicMirror: -[SketchPluginContext unobserveSelection] [Line 221] Unobserving 0
5/9/16 8:22:49.658 PM Sketch[12046]: MagicMirror: -[SketchPluginContext observeSelection] [Line 230] observing 0
5/9/16 8:22:49.658 PM Sketch[12046]: stack count: 0
5/9/16 8:22:54.533 PM Sketch[12046]: MagicMirror: -[SketchPluginContext windowDidBecomeMain:] [Line 75] windowDidBecomeMain
5/9/16 8:22:54.533 PM Sketch[12046]: MagicMirror: -[SketchPluginContext unobserveSelection] [Line 221] Unobserving 0
5/9/16 8:22:54.915 PM Sketch[12046]: MagicMirror: -[MagicMirror(SketchEventsController) documentDidChange:] [Line 507] document <MSDocument: 0x7fa92143dc20>
5/9/16 8:22:54.915 PM Sketch[12046]: MagicMirror: -[SketchPluginContext layerSelectionDidChange:] [Line 199] layerSelectionDidChange: (null)
5/9/16 8:22:54.915 PM Sketch[12046]: MagicMirror: -[SketchPluginContext unobserveSelection] [Line 221] Unobserving 0
5/9/16 8:22:54.915 PM Sketch[12046]: MagicMirror: -[SketchPluginContext observeSelection] [Line 230] observing 0
5/9/16 8:22:54.916 PM Sketch[12046]: stack count: 0
5/9/16 8:22:56.310 PM Sketch[12046]: MagicMirror: -[MagicMirror goAway] [Line 222] goAway
5/9/16 8:22:56.310 PM Sketch[12046]: MagicMirror: -[MMWindowController dealloc] [Line 74] MMWindowController: dealloc
`

**Comment by sogen** [comment]
a better formatted file:
[sketch-magicmirror-crash-log.txt](https://github.com/jamztang/MagicMirror/files/256193/sketch-magicmirror-crash-log.txt)

**Comment by jamztang** [comment]
Thanks! The log looks like the plugin is able to run and show the window but the window goes away quickly as if something was closing it. It doesn't seemed to have "crash" tho, I will try to investigate and hopefully update you guys soon..

**Comment by jamztang** [comment]
Hey guys, if you happened to install by copying the whole folder, please instead just double click the .sketchplugin to install so that it would rest in the root of the plugin folder. There were some issue where the framework doesn't load probably when I a sub dir @zilos

**Comment by zilos** [comment]
@jamztang still crashes. I did have the folder in there as well, but now it only has the plugin in the root folder, and it still crashes.

**Comment by sogen** [comment]
here too, it has been in root folder

**Comment by jamztang** [comment]
@zilos just to make sure. the version that doesn't worked on your computer is on Yosemite, is that right?

**Comment by zilos** [comment]
@jamztang yes, im on Yosemite

**Comment by hirakujira** [comment]
here too. However when I tried to enable magic mirror, it shows nothing and nothing happened. Then when I tried to enable it again, it crashes. 
Sketch v3.8.1 
MagicMirror v2.0.6
OS X 10.11.5

**Comment by jamztang** [comment]
Hi guys I've updated the Plugin to v2.0.7.

Please make sure you have a clean installation, follow 1 & 2 & 3 in this guide
https://github.com/jamztang/MagicMirror/wiki/Troubleshooting

And if nothing works, try running the plugin in safe mode (the 4# in the guide)
https://github.com/jamztang/MagicMirror/wiki/Running-Plugin-in-Safe-Mode

Please let me know if that helps...

**Comment by sogen** [comment]
Hi, sorry to say, but 2.0.7 still crashes, both the .zip from Github and the DMG with 2.0.7.
It also crashes when clicking the Close(X) button in the bar. 
Also going to the top menu MagicMirror>Enable/Disable crashes Sketch
Also using it in safe mode crashes it.

**Comment by zilos** [comment]
@jamztang so I tried everything you mentioned here and nothing works. It keeps crashing.

**Comment by jamztang** [comment]
Guys thanks for your patient on this.

I think we are eliminating quite a bit of reasons that may results in crashes here.

- Installing from Sketch toolbox should be resolved
- Check for updates should have turned off in safe mode
- Framework has been recompiled for Yosemite in previous version

Most users I know have been working for them, I must have been overlooked something simple. I really wish I have a chance to do a remote session on resolve this in person with you guys.

Did you guys tried 
1. Deregister and try the free version
2. reinstall Sketch?!

**Comment by jamztang** [comment]
In addition, use it without using the office Wifi? I am not sure there's anything about this, just some two cents

**Comment by sogen** [comment]
Hi, none of that worked.
I even tried turning off sandboxing but didn't help
attaching log that shows when closing(quit) sketch
[log.txt](https://github.com/jamztang/MagicMirror/files/288590/log.txt)

have you tried the sketch devs forum?
http://mail.sketchplugins.com/mailman/listinfo/dev_sketchplugins.com

**Comment by sogen** [comment]
close!

**Comment by zilos** [comment]
sorry to keep bringing this up but this plugin doesnt not work at all for me. It crashes every time. It used to work fine for me but now, it just crashes always. Is there anything you can do? I tried all your suggestions and still, no luck. 

Running Sketch Version 39.1 (31720)
Magic Mirror V.2.0.9

thanks again!

**Comment by sogen** [comment]
hi, 2.0.9 crashes on Yosemite

**Comment by lisazeitlhuber** [comment]
@jamztang Same here. When using the plugin sketch crashed - 4 times in a row - immediately. did sketch stop supporting your plugin?

**Comment by lisazeitlhuber** [comment]
ok got it - I updated it with the new plugin! Works

**Comment by sogen** [comment]
AFAIR Sketch changed  some functions some time ago, maybe its related to that.

**Comment by jamztang** [comment]
Hey guys 2.0.9.4 should fix existing crashes with Sketch 42

As for your interest, we have also created a completely new version 3.0 of magic mirror, please head to our site for more info.

http://magicsketch.io/mirror

**Comment by lisazeitlhuber** [comment]
Hi James,

Did you see my email about the license key that does not work anymore?

It comes from lisa.zeitlhuber@gmail.com

Thank you!


Lisa Zeitlhuber

**Comment by jamztang** [comment]
Hi Liza,

We are investigating will get back to you soon 

Thanks!

James

**Comment by JulieTorrisi** [comment]
@jamztang I'm also having issues with sketch crashing when I launch magic mirror. I have sketch 42 and magic mirror 3.0. help!

**Comment by shawntraylor** [comment]
@jamztang I'm having the same issue too with Sketch 42 and 2.0.9.4. Constantly crashes.Please help.
